### ISSUE TITLE
Cant connect

### ISSUE THREAD

**Issue by LilCrispy2o9** [PocketDock/PocketDockConsole#7]
I cant connect and on the server it gives me this!

Warning: pack(): Type N: too few arguments in phar:///home/tcagame_svc838/angelov/838/plugins/PocketDockConsole_bcd5d5d31a1c.phar/src/PocketDockConsole/SocksServer.php on line 258

**Comment by mslayton** [comment]
I love the idea of this plugin -- alas, it isn't working for me.  

Despite having changed my rcon.password to a new string in server.properties, I can log into the host using the port on 9090, but not matter what I type, I get the message:  "Failed login attempt, this event will be recorded!".   The server also records the failed login in its log. 

MCPE version:  PocketMine-MP Final_1.4 (build 916) using API 1.10.0

Hope that can be fixed -- looks like a great util!  :0)

**Comment by Humerus** [comment]
Change the password in the file that's located in your plugin directory then under the directory PocketDockConsole. The file is named config.yml and has only a few parameters. The server uses the password in that file in order to authenticate. The rcon.password in the server.properties file is only used for the first login.

**Comment by mslayton** [comment]
Thanks, that did the trick.

Didn't notice the extra setting in config.yml.   My bad.

Cheers --
